version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8503:8503"
    volumes:
      - ./backend/reports:/app/reports
    networks:
      - cleandex-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - cleandex-net

networks:
  cleandex-net:
